use std::{
    collections::{BTreeMap, BTreeSet},
    fs::{self, OpenOptions},
    io::Write,
    os::unix::fs::OpenOptionsExt,
    path::Path,
};

use anyhow::{Context, Result};
use serde::Serialize;
use spark_schema::{MetricPoint, Quality};

const REASON_INVALID: &str = "DISCOVERY_INVALID";
const REASON_VALID_UNCHANGING: &str = "DISCOVERY_VALID_UNCHANGING";

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct DiscoveryKey {
    source: String,
    metric: String,
    attributes: BTreeMap<String, String>,
}

#[derive(Debug, Default)]
struct Observation {
    successful_values: BTreeSet<u64>,
    failures: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Classification {
    ValidChanging,
    ValidUnchanging,
    Invalid,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(crate) struct DiscoverySummary {
    pub(crate) valid_changing: usize,
    pub(crate) valid_unchanging: usize,
    pub(crate) invalid: usize,
}

#[derive(Debug, Default)]
pub(crate) struct DiscoveryTracker {
    observations: BTreeMap<DiscoveryKey, Observation>,
}

impl DiscoveryTracker {
    pub(crate) fn observe(&mut self, points: &[MetricPoint]) {
        for point in points {
            let observation = self
                .observations
                .entry(DiscoveryKey::from(point))
                .or_default();
            if point.value.is_some()
                && matches!(
                    point.quality,
                    Quality::Measured | Quality::Derived | Quality::Estimated
                )
            {
                if let Some(value) = point.value {
                    observation.successful_values.insert(value.to_bits());
                }
            } else {
                observation.failures = observation.failures.saturating_add(1);
            }
        }
    }

    pub(crate) fn write_policy(&self, path: &Path) -> Result<DiscoverySummary> {
        let (output, summary) = self.output();
        let encoded = toml::to_string_pretty(&output).context("encoding discovery policy TOML")?;
        let parent = path
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
            .unwrap_or_else(|| Path::new("."));
        if !parent.is_dir() {
            anyhow::bail!(
                "discovery output parent does not exist: {}",
                parent.display()
            );
        }
        let file_name = path
            .file_name()
            .context("discovery output path has no file name")?
            .to_string_lossy();
        let temporary = parent.join(format!(".{file_name}.tmp-{}", std::process::id()));
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o640)
            .open(&temporary)
            .with_context(|| format!("creating discovery output {}", temporary.display()))?;
        let contents = format!(
            "# Generated by spark-agent signal discovery. Review before installation.\n{encoded}"
        );
        file.write_all(contents.as_bytes())
            .context("writing discovery policy")?;
        file.sync_all().context("syncing discovery policy")?;
        fs::rename(&temporary, path).with_context(|| {
            format!(
                "installing discovery output {} as {}",
                temporary.display(),
                path.display()
            )
        })?;
        Ok(summary)
    }

    fn output(&self) -> (GeneratedPolicyFile, DiscoverySummary) {
        let mut summary = DiscoverySummary::default();
        let mut signal_policy = Vec::new();
        for (key, observation) in &self.observations {
            match observation.classification() {
                Classification::ValidChanging => {
                    summary.valid_changing += 1;
                }
                Classification::ValidUnchanging => {
                    summary.valid_unchanging += 1;
                    signal_policy.push(GeneratedPolicy::new(key, REASON_VALID_UNCHANGING));
                }
                Classification::Invalid => {
                    summary.invalid += 1;
                    signal_policy.push(GeneratedPolicy::new(key, REASON_INVALID));
                }
            }
        }
        (GeneratedPolicyFile { signal_policy }, summary)
    }
}

impl Observation {
    fn classification(&self) -> Classification {
        match self.successful_values.len() {
            0 => Classification::Invalid,
            1 => Classification::ValidUnchanging,
            _ => Classification::ValidChanging,
        }
    }
}

impl From<&MetricPoint> for DiscoveryKey {
    fn from(point: &MetricPoint) -> Self {
        Self {
            source: point.source.clone(),
            metric: point.name.clone(),
            attributes: point.attributes.clone(),
        }
    }
}

#[derive(Debug, Serialize)]
struct GeneratedPolicyFile {
    signal_policy: Vec<GeneratedPolicy>,
}

#[derive(Debug, Serialize)]
struct GeneratedPolicy {
    source: String,
    metric: String,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    attributes: BTreeMap<String, String>,
    policy: String,
    reason: String,
}

impl GeneratedPolicy {
    fn new(key: &DiscoveryKey, reason: &str) -> Self {
        Self {
            source: key.source.clone(),
            metric: key.metric.clone(),
            attributes: key.attributes.clone(),
            policy: "disabled".to_owned(),
            reason: reason.to_owned(),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::*;

    static NEXT_OUTPUT: AtomicU64 = AtomicU64::new(0);

    fn gauge(value: f64, domain: &str) -> MetricPoint {
        MetricPoint::gauge(
            "nvidia.gpu.clock.frequency",
            value,
            "MHz",
            Quality::Measured,
            "nvml",
        )
        .with_attribute("clock.domain", domain)
    }

    fn unavailable(domain: &str) -> MetricPoint {
        MetricPoint::unavailable(
            "nvidia.gpu.clock.frequency",
            "MHz",
            Quality::Unsupported,
            "nvml",
            "NVML_NOTSUPPORTED",
        )
        .with_attribute("clock.domain", domain)
    }

    fn output_path() -> std::path::PathBuf {
        let id = NEXT_OUTPUT.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!("spark-discovery-{}-{id}.toml", std::process::id()))
    }

    #[test]
    fn classifies_changing_unchanging_and_invalid_series() {
        let mut tracker = DiscoveryTracker::default();
        tracker.observe(&[
            gauge(100.0, "graphics"),
            gauge(200.0, "memory"),
            unavailable("video"),
        ]);
        tracker.observe(&[
            gauge(101.0, "graphics"),
            gauge(200.0, "memory"),
            unavailable("video"),
        ]);
        let (output, summary) = tracker.output();
        assert_eq!(summary.valid_changing, 1);
        assert_eq!(summary.valid_unchanging, 1);
        assert_eq!(summary.invalid, 1);
        assert_eq!(output.signal_policy.len(), 2);
        assert!(
            output
                .signal_policy
                .iter()
                .any(|entry| entry.reason == REASON_VALID_UNCHANGING)
        );
        assert!(
            output
                .signal_policy
                .iter()
                .any(|entry| entry.reason == REASON_INVALID)
        );
    }

    #[test]
    fn one_success_remains_valid_even_after_failures() {
        let mut tracker = DiscoveryTracker::default();
        tracker.observe(&[gauge(100.0, "memory")]);
        tracker.observe(&[unavailable("memory")]);
        let (_, summary) = tracker.output();
        assert_eq!(summary.valid_unchanging, 1);
        assert_eq!(summary.invalid, 0);
    }

    #[test]
    fn writes_a_directly_loadable_policy_with_complete_attributes() {
        let mut tracker = DiscoveryTracker::default();
        tracker.observe(&[unavailable("memory")]);
        let path = output_path();
        let _ = fs::remove_file(&path);
        let summary = tracker.write_policy(&path).unwrap();
        assert_eq!(summary.invalid, 1);
        let raw = fs::read_to_string(&path).unwrap();
        assert!(raw.contains("DISCOVERY_INVALID"));
        assert!(raw.contains("clock.domain"));
        let parent = path.parent().unwrap();
        let directory = parent.join(format!(
            "spark-discovery-policy-dir-{}-{}",
            std::process::id(),
            NEXT_OUTPUT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir(&directory).unwrap();
        fs::rename(&path, directory.join("discovered.toml")).unwrap();
        assert!(crate::signal_policy::SignalEmitter::load(Some(&directory)).is_ok());
        fs::remove_dir_all(directory).unwrap();
    }
}
